// request
const REQUEST_POSTS = 'REQUEST_POSTS';
const RECEIVE_POSTS = 'RECEIVE_POSTS';
const INVALIDATE_POSTS = 'INVALIDATE_POSTS';

// counter
const INCREASE = 'INCREASE';
const DECREASE = 'DECREASE';

// curCity
const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
const SET_CURCITY = 'SET_CURCITY';
const SET_LOCAL_CITYS = 'SET_LOCAL_CITYS';

export {
  REQUEST_POSTS,
  RECEIVE_POSTS,
  INVALIDATE_POSTS,

  INCREASE,
  DECREASE,

  GET_WEATHER_DATA,
  SET_CURCITY,
  SET_LOCAL_CITYS,
};
